# Generated by Django 5.0.6 on 2024-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('reader', 'Читатель'), ('author', 'Автор')], default='reader', max_length=10, verbose_name='Profile Type'),
        ),
    ]
