# Generated by Django 5.0.6 on 2024-07-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
