# Generated by Django 5.0.6 on 2024-07-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_tag_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Год издания'),
        ),
    ]
